version: "1.0"

services:
  app:
    build:
      context: ./app
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./app/.env    
    ports:
      - "8000:8000"
  db:
    build:
      context: ./app/db
    env_file:
      - ./app/.env
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5    

networks:
  backend:
    driver: bridge
  