version: "3.3"

services:
  postgres:
    build:
      context: .
      dockerfile: pg.Dockerfile
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - 8000:80
    environment:
      - DB_URL=postgresql+psycopg2://postgres:postgres@postgres:5432/postgres
volumes:
  pgdata:
