version: '3.8'
services:
  db:
    build: ./postgres-custom
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/1-init.sql

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_USER: your_username
      DB_PASSWORD: your_password
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: your_database

volumes:
  db-data: